volumes:
  test_data:
services:
  db:
    container_name: db-test
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devPassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - test_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  frontend:
    container_name: frontend-test
    image: frontend-test
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - "3000:3000"

  frontend1:
    container_name: frontend1-test
    image: frontend1-test
    build:
      context: ./frontend1
      target: development
    volumes:
      - ./frontend1/src:/frontend1/src
      - ./frontend1/public:/frontend1/public
    ports:
      - "5173:5173"

  frontend2:
    container_name: frontend2-test
    image: frontend2-test
    build:
      context: ./frontend2
      target: development
    volumes:
      - ./frontend2/src:/frontend2/src
      - ./frontend2/public:/frontend2/public
    ports:
      - "5174:5174"

  frontend3:
    container_name: frontend3-test
    image: frontend3-test
    build:
      context: ./frontend3
      target: development
    volumes:
      - ./frontend3/src:/frontend3/src
      - ./frontend3/public:/frontend3/public
    ports:
      - "4321:4321"

  frontend4:
    container_name: frontend4-test
    image: frontend4-test
    build:
      context: ./frontend4
      target: development
    volumes:
      - ./frontend4/src:/frontend4/src
      - ./frontend4/public:/frontend4/public
    ports:
      - "3002:3002"
      
  b4f:
    container_name: b4f-test
    image: b4f-test
    build:
      context: ./b4f
      target: development
    volumes:
      - ./b4f:/b4f
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    ports:
      - "3001:3001"

  backend:
    container_name: backend-test
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
