volumes:
  test_data:
services:
  db:
    container_name: db-test
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devPassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - test_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  frontend:
    container_name: frontend-test
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    container_name: backend-test
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - "8000:8000"
