# Docker Compose - Backend Services Only
# Perfect for API development and testing

volumes:
  test_data:

services:
  db:
    container_name: db-test
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devPassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - test_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    container_name: backend-test
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173

  b4f:
    container_name: b4f-test
    image: b4f-test
    build:
      context: ./b4f
      target: development
    volumes:
      - ./b4f:/b4f
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:devPassword@db:5432/postgres?schema=public

  b4f1:
    container_name: b4f1-test
    image: b4f1-test
    build:
      context: ./b4f1
      target: development
    volumes:
      - ./b4f1:/b4f1
    depends_on:
      - db
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:devPassword@db:5432/postgres?schema=public
