"""Add orders and payment models v2

Revision ID: 32298309fcd3
Revises: 6274aa0acfb3
Create Date: 2025-09-27 19:40:35.608466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32298309fcd3'
down_revision: Union[str, None] = '6274aa0acfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('amount_total', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('payment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_logs_event_id'), 'payment_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_payment_logs_event_type'), 'payment_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_logs_session_id'), 'payment_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_payment_logs_user_id'), 'payment_logs', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_product_id', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('price_amount', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id'),
    sa.UniqueConstraint('stripe_product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_logs_user_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_session_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_event_type'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_event_id'), table_name='payment_logs')
    op.drop_table('payment_logs')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
