"""Add orders and payment models

Revision ID: 6274aa0acfb3
Revises: 03180c3b47a8
Create Date: 2025-09-27 19:39:47.036622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6274aa0acfb3'
down_revision: Union[str, None] = '03180c3b47a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
